// I need it in a separate file only to use
// using static TokenType.
public enum TokenType : ushort {
    Plus          = '+',
    Minus         = '-',
    Mul           = '*',
    Div           = '/',
    Equals        = '=',
    Exp           = '^',
    Mod           = '%',
    OParen        = '{',
    CParen        = '}',
    ORParen       = '(',
    CRParen       = ')',
    OSQParen      = '[',
    CSQParen      = ']',
    Colon         = ':',
    Semicolon     = ';',
    And           = '&',
    Or            = '|',
    Hash          = '#',
    At            = '@',
    SQuote        = '\'',
    DQuote        = '"',
    Dot           = '.',
    Comma         = ',',
    MoreThan      = '>',
    LessThan      = '<',
    Excpoint      = '!',
    Ident         = 256,
    EndOfFile     = 257,
    Return        = 258,
    Literal       = 259,
    StringLiteral = 260,
    CharLiteral   = 261,
    Struct        = 262,
    Void          = 263,
    Null          = 263,
}