// I need it in a separate file only to use
// using static TokenType.
public enum TokenType : ushort {
    Plus          = '+',
    Minus         = '-',
    Mul           = '*',
    Div           = '/',
    Equals        = '=',
    Exp           = '^',
    Mod           = '%',
    OParen        = '{',
    CParen        = '}',
    ORParen       = '(',
    CRParen       = ')',
    OSQParen      = '[',
    CSQParen      = ']',
    Colon         = ':',
    Semicolon     = ';',
    And           = '&',
    Or            = '|',
    Hash          = '#',
    Psina         = '@',
    SQuote        = '\'',
    DQuote        = '"',
    Dot           = '.',
    Comma         = ',',
    MoreThan      = '>',
    LessThan      = '<',
    Excpoint      = '!',
    Ident         = 256,
    EndOfFile     = 257,
    Return        = 258,
    IntLiteral    = 259,
    FloatLiteral  = 260,
    DoubleLiteral = 261,
    StringLiteral = 262,
    CharLiteral   = 263,
    Struct        = 264,
    Void          = 265,
    Null          = 266,
    Unknown       = 267,
    DoubleColon   = 268,
    ArrowRight    = 269,
}